#!/usr/bin/env bash
# AXP install hook for mintbot-mcp (also standalone-runnable, SPEC section 10).
# Idempotent: re-running converges the virtualenv, the package files, the
# launcher and the bearer token.
#
# Under an AXP host the daemon is the host's: the manifest binds the service
# with a `command`, so the host writes, contains and supervises the systemd
# unit itself and this script MUST NOT start the daemon (SPEC section 5.3).
# Run by hand (no AXP_HOST) as root on a systemd machine, the script installs
# a plain `mintbot-mcp.service` instead.
set -euo pipefail

log() { printf '[mintbot-mcp] %s\n' "$*"; }
die() { log "ERROR: $*" >&2; exit 1; }
SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- host <-> script contract (AXP SPEC section 6) ---------------------------
# Every AXP_* variable is optional: an AXP host sets them, a human running the
# script by hand gets the spec defaults below (standalone rule, SPEC section 10).
PUBLISHER="mintbot.ai"
NAME="mintbot-mcp"
if [ -n "${AXP_PREFIX:-}" ]; then
  PREFIX="${AXP_PREFIX}"
elif [ "$(id -u)" -eq 0 ]; then
  PREFIX="/opt/${NAME}"
else
  PREFIX="${HOME}/.local/opt/${NAME}"
fi
if [ -n "${AXP_STATE_DIR:-}" ]; then
  STATE_DIR="${AXP_STATE_DIR}"
elif [ "$(id -u)" -eq 0 ]; then
  STATE_DIR="/var/lib/axp/${PUBLISHER}/${NAME}"
else
  STATE_DIR="${HOME}/.local/state/axp/${PUBLISHER}/${NAME}"
fi
export AXP_STATE_DIR="${STATE_DIR}"          # the daemon and the CLI read the same variable
LAUNCHER="${PREFIX}/bin/mintbot-mcp"
# The standalone unit (no AXP host). An AXP host binds the daemon through the
# manifest's `command` and writes a unit of its own (SPEC section 5.3).
UNIT_NAME="mintbot-mcp.service"
UNIT_FILE="${MINTBOT_MCP_UNIT_DIR:-/etc/systemd/system}/${UNIT_NAME}"

PYTHON="${MINTBOT_MCP_PYTHON:-python3}"
command -v "${PYTHON}" >/dev/null 2>&1 || die "python3 is required (Debian: apt install python3 python3-venv)"

# pip writes its cache under ~/.cache by default, which a sandboxing host keeps
# read-only; the cache dir the host hands over is exactly for this.
if [ -n "${AXP_CACHE_DIR:-}" ]; then
  mkdir -p "${AXP_CACHE_DIR}/pip"
  export PIP_CACHE_DIR="${AXP_CACHE_DIR}/pip"
fi

log "installing into ${PREFIX}"
install -d -m 0755 "${PREFIX}" "${PREFIX}/bin" "${PREFIX}/lib/mintbot_mcp"
install -d -m 0700 "${STATE_DIR}"

if [ ! -x "${PREFIX}/venv/bin/python" ]; then
  log "creating the private virtualenv"
  "${PYTHON}" -m venv "${PREFIX}/venv" || die "could not create a virtualenv (Debian: apt install python3-venv)"
fi
log "installing pinned Python dependencies"
"${PREFIX}/venv/bin/pip" install --disable-pip-version-check --quiet --requirement "${SOURCE_DIR}/requirements.txt"

log "installing the package"
# Converge: modules of an earlier version must not linger next to the new ones.
rm -rf "${PREFIX}/lib/mintbot_mcp"
install -d -m 0755 "${PREFIX}/lib/mintbot_mcp"
install -m 0644 "${SOURCE_DIR}"/mintbot_mcp/*.py "${PREFIX}/lib/mintbot_mcp/"
install -m 0644 "${SOURCE_DIR}/README.md" "${SOURCE_DIR}/LICENSE" "${SOURCE_DIR}/after-install.md" \
  "${SOURCE_DIR}/requirements.txt" "${PREFIX}/"
# Lifecycle scripts are kept under the install prefix so a standalone install
# can upgrade / uninstall / health-check itself later. An AXP host additionally
# retains the whole artifact (AXP_ARTIFACT_DIR) and runs hooks from there.
for script in install.sh upgrade.sh uninstall.sh healthcheck.sh; do
  install -m 0755 "${SOURCE_DIR}/${script}" "${PREFIX}/${script}"
done

log "writing the launcher ${LAUNCHER}"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  '# Generated by install.sh: runs mintbot-mcp from its private virtualenv.' \
  'set -euo pipefail' \
  "export PYTHONPATH=\"${PREFIX}/lib\${PYTHONPATH:+:\${PYTHONPATH}}\"" \
  "exec \"${PREFIX}/venv/bin/python\" -m mintbot_mcp \"\$@\"" \
  > "${LAUNCHER}.tmp"
chmod 0755 "${LAUNCHER}.tmp"
mv -f "${LAUNCHER}.tmp" "${LAUNCHER}"

log "ensuring the bearer token at ${STATE_DIR}/token"
"${LAUNCHER}" token >/dev/null

if [ -n "${AXP_HOST:-}" ]; then
  log "AXP host ${AXP_HOST} owns the service unit; the daemon is not started here"
elif [ "$(id -u)" -eq 0 ] && command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  log "installing ${UNIT_NAME}"
  install -d -m 0755 "$(dirname "${UNIT_FILE}")"
  printf '%s\n' \
    "# Written by ${PREFIX}/install.sh (standalone mintbot-mcp install); removed by uninstall.sh." \
    '[Unit]' \
    'Description=mintbot-mcp: MCP server for this mintbot agent' \
    'After=network-online.target' \
    'Wants=network-online.target' \
    '' \
    '[Service]' \
    'Type=simple' \
    "ExecStart=${LAUNCHER} serve" \
    "Environment=AXP_STATE_DIR=${STATE_DIR}" \
    "WorkingDirectory=${PREFIX}" \
    'Restart=always' \
    'RestartSec=2' \
    'NoNewPrivileges=yes' \
    'PrivateTmp=yes' \
    'ProtectSystem=strict' \
    'ProtectHome=read-only' \
    "ReadWritePaths=${STATE_DIR} ${PREFIX}" \
    '' \
    '[Install]' \
    'WantedBy=multi-user.target' \
    > "${UNIT_FILE}.tmp"
  mv -f "${UNIT_FILE}.tmp" "${UNIT_FILE}"
  systemctl daemon-reload
  systemctl enable --quiet "${UNIT_NAME}"
  systemctl restart "${UNIT_NAME}"
  log "${UNIT_NAME} is enabled and running"
else
  log "no systemd available here; start the server with: ${LAUNCHER} serve"
fi
log "installation complete; run '${LAUNCHER} client-config' for a ready-to-paste MCP client block"
